# Generated by Django 3.2 on 2021-04-10 10:46

import apps.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to=apps.menu.models.menu_image_file_path),
        ),
    ]
