# Generated by Django 3.2 on 2021-04-27 10:41

import apps.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='lang',
            field=models.CharField(default='EN', max_length=10),
        ),
        migrations.AddField(
            model_name='menu',
            name='translated_image',
            field=models.ImageField(null=True, upload_to=apps.menu.models.translated_image_file_path),
        ),
    ]
