# Generated by Django 3.2 on 2021-04-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210427_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
