# Generated by Django 3.2 on 2021-04-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='original',
            field=models.TextField(blank=True, null=True),
        ),
    ]
